version: 2

before:
  hooks:
    - go mod tidy
    - cd lambda && go mod tidy

builds:
  - id: neptune
    main: .
    binary: neptune
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

  - id: lambda
    dir: lambda
    main: .
    binary: bootstrap
    goos:
      - linux
    goarch:
      - amd64

archives:
  - ids:
      - neptune
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

  - id: lambda-archive
    ids:
      - lambda
    format: zip
    name_template: neptune-webhook
    strip_binary_directory: true
    wrap_in_directory: false

checksum:
  name_template: checksums.txt

changelog:
  use: github
  sort: asc
