repository:
  object_storage: gs://object_storage_url
  stacks_management: terramate
  branch: main
  plan_requirements:
    - undiverged
  apply_requirements:
    - approved
    - mergeable
    - undiverged
  allowed_workflow: default

workflows:
  default:
    plan:
      steps:
        - run: echo "Custom command"
          once: true
        - run: terramate run --parallel $(nproc --all) --changed -- terragrunt init -upgrade
          once: true
        - run: terramate run --changed -- terragrunt plan
          once: true
    apply:
      depends_on:
        - plan
      steps:
        - run: echo "Custom command"
          once: true
        - run: terragrunt apply -auto-approve
          once: false
