log_level: DEBUG

repository:
  object_storage: s3://neptune-e2e
  branch: main
  plan_requirements: []
  apply_requirements: []
  allowed_workflow: default
  stacks_management: terramate

workflows:
  default:
    plan:
      steps:
        - run: terraform init -input=false
        - run: terraform plan -input=false -out=tfplan
    apply:
      depends_on:
        - plan
      steps:
        - run: terraform apply -input=false tfplan
