repository:
  object_storage: s3://your-bucket
  branch: main
  plan_requirements:
    - undiverged
  apply_requirements:
    - approved
    - mergeable
    - undiverged
  allowed_workflow: default

workflows:
  default:
    plan:
      steps:
        - run: terragrunt init -upgrade
        - run: terragrunt plan
    apply:
      depends_on:
        - plan
      steps:
        - run: terragrunt apply -auto-approve
