name: e2e

on:
  push:
    branches:
      - main
      - "release-**"
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main
      - "release-**"

permissions:
  contents: read
  pull-requests: read

jobs:
  changes:
    outputs:
      should-run: ${{ steps.changes.outputs.e2e == 'true' }}
    if: github.event.pull_request.draft == false || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
        id: changes
        with:
          filters: |
            e2e:
              - 'e2e/**'
              - 'internal/**'
              - 'lambda/**'
              - 'cmd/**'
              - 'docker-compose*.yaml'
              - 'docker-compose*.yml'
              - '.github/workflows/e2e.yml'
              - 'go.*'

  e2e:
    needs: [changes]
    if: needs.changes.outputs.should-run == 'true'
    name: e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
        with:
          go-version-file: go.mod

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4
        with:
          terraform_version: "1.5.0"

      - name: Run e2e
        run: ./e2e/scripts/run-terramate.sh
        env:
          AWS_ACCESS_KEY_ID: minioadmin
          AWS_SECRET_ACCESS_KEY: minioadmin
          AWS_REGION: us-east-1
          AWS_ENDPOINT_URL_S3: http://localhost:9000

  skip:
    needs: [changes]
    if: needs.changes.outputs.should-run == 'false'
    runs-on: ubuntu-latest
    steps:
      - run: echo "No e2e-relevant changes, skipping e2e"
