name: e2e

on:
  push:
    branches:
      - main
      - "release-**"
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main
      - "release-**"

# concurrency:
#   group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
#   cancel-in-progress: false

permissions:
  contents: read
  pull-requests: read

jobs:
  changes:
    outputs:
      should-run: ${{ steps.changes.outputs.e2e == 'true' }}
    if: github.event.pull_request.draft == false || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
        id: changes
        with:
          filters: |
            e2e:
              - 'e2e/**'
              - 'internal/**'
              - 'lambda/**'
              - 'cmd/**'
              - 'docker-compose*.yaml'
              - 'docker-compose*.yml'
              - '.github/workflows/e2e.yml'
              - 'go.*'

  e2e:
    needs: [changes]
    if: needs.changes.outputs.should-run == 'true'
    name: e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_version: "1.5.0"

      - name: Run e2e
        run: ./e2e/scripts/run-terramate.sh
        env:
          AWS_ACCESS_KEY_ID: minioadmin
          AWS_SECRET_ACCESS_KEY: minioadmin
          AWS_REGION: us-east-1
          AWS_ENDPOINT_URL_S3: http://localhost:9000

  skip:
    needs: [changes]
    if: needs.changes.outputs.should-run == 'false'
    runs-on: ubuntu-latest
    steps:
      - run: echo "No e2e-relevant changes, skipping e2e"
