name: test

on:
  push:
    branches:
      - main
      - "release-**"
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main
      - "release-**"

# concurrency:
#   group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
#   cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  changes:
    permissions:
      contents: read
      pull-requests: read
    outputs:
      should-run: ${{ steps.changes.outputs.go == 'true' }}
    if: github.event.pull_request.draft == false || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
        id: changes
        with:
          filters: |
            go:
              - '**.go'
              - 'go.*'
              - 'Makefile'
              - '.github/workflows/test.yml'

  test:
    needs: [changes]
    if: needs.changes.outputs.should-run == 'true'
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod
      - run: make test-all
      - run: make lambda.test
      - run: make check-fmt

  skip:
    needs: [changes]
    if: needs.changes.outputs.should-run == 'false'
    runs-on: ubuntu-latest
    steps:
      - run: echo "No Go changes, skipping tests"
